@baseUrl = http://localhost:3000

@cookie = auth="86a48dc5-04d4-4ddb-b97b-31fde0321d57"

###
PUT {{baseUrl}}/user-edit
Content-Type: application/json
Cookie: {{cookie}}

{
  "user_currency": "$",
  "user_email": "test@test.com",
  "user_name": "test2"
}